#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'haml'
require 'tilt'
require 'helpers/haml_helper'
haml_base = 'guide/src/haml/'

compile = lambda { |changed_file|
  helper = HamlHelper.new
  template = Tilt::HamlTemplate.new(haml_base + 'layout.haml')
  
  # english
  helper.base_path = haml_base + 'english/'
  Dir[helper.base_path + '[^_]*.haml'].each do |page_path|
    rendered = template.render(helper){
      Tilt::HamlTemplate.new(page_path).render(helper)
    }
    
    basename = File.basename(page_path, '.haml')
    File.open('guide/public/' + basename + '.html', 'w+'){|f| f.write(rendered)}
  end
  
  if changed_file
    `open -g guide/public/#{File.basename(changed_file).sub(/\.haml/, '.html')}`
  else
    `open -g guide/public/index.html`
  end
}

if ARGV.include?('--watch')
  require 'filewatcher'
  FileWatcher.new(Dir[haml_base + "**/*.haml"]).watch(0.2) do |file|
    compile.call(file)
  end
else
  compile.call
end